# Generated by Django 5.1.7 on 2025-03-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='available_routes',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='trip',
            name='duration',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='fuel_stops',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='trip',
            name='water_alerts',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='trip',
            name='cycle_hours',
            field=models.FloatField(),
        ),
    ]
