# Generated by Django 5.1.7 on 2025-03-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_trip_available_routes_trip_duration_trip_fuel_stops_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='dropoff_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='pickup_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
